<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sathish" failures="1" tests="3" name="test1" time="23.584" errors="0" timestamp="2024-08-12T18:48:57 IST">
  <testcase classname="VD46.TestClass" name="testLogo" time="0.236"/>
  <testcase classname="VD46.TestClass" name="testAppUrl" time="0.025">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at VD46.TestClass.testAppUrl(TestClass.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="VD46.TestClass" name="testHomePageTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testHomePageTitle -->
</testsuite> <!-- test1 -->
